HAI 1.3 
	CAN HAS STDIO?
	I HAS A NUMPURR ITZ A NUMBR
	IM IN YR LOOP 
		GIMMEH NUMPURR
		NUMPURR IS NOW A NUMBR
		BOTH SAEM NUMPURR AN 42, O RLY?
			YA RLY
				GTFO
		OIC
		VISIBLE NUMPURR
	IM OUTTA YR LOOP
KTHXBYE